
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.Normalizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Form_Laundry extends javax.swing.JFrame {

    public Form_Laundry() {
        initComponents();

        Tampilkan_Data();
    }

    private Connection conn = new Koneksi().Connect();
    private DefaultTableModel tabmodel;

    public int Total_Harga;
    public int field_id;

    public void reset() {
        
        txt_namaPembeli.setText("");
        combo_jenis.setSelectedIndex(0);
        txt_harga.setText("");
        txt_berat.setText("");
        txt_ttlHarga.setText("");
        txt_bayar.setText("");
        field_id = 0;
    }

    public void Tampilkan_Data() {
        String[] Data = {"ID Transaksi","Pembeli","Jenis Cuci", "Harga/Kilo", "Berat", "Total Harga", "Bayar"};
        tabmodel = new DefaultTableModel(null, Data);
        tabel_data.setModel(tabmodel);
            for (int i = 0; i < tabel_data.getColumnCount(); i++) {
                Class<?> col_class = tabel_data.getColumnClass(i);
                    tabel_data.setDefaultEditor(col_class, null); // Mengatur editor menjadi null
            }

        String sql = "select*from data_laundry";
        try {
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String namaPembeli = hasil.getString("namaPembeli");
                String FieldId = String.valueOf(hasil.getInt("field_id"));
                String JenisCuci = hasil.getString("jenis_cuci");
                String Harga = hasil.getString("harga");
                String Berat = hasil.getString("berat");
                String TotalHarga = hasil.getString("total_harga");
                String Bayar = hasil.getString("bayar");
                String[] DataLaundry = {FieldId,namaPembeli, JenisCuci, Harga, Berat, TotalHarga, Bayar};
                tabmodel.addRow(DataLaundry);
            }
        } catch (SQLException e) {
            Logger.getLogger(Normalizer.Form.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combo_jenis = new javax.swing.JComboBox<>();
        txt_bayar = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        txt_berat = new javax.swing.JTextField();
        txt_ttlHarga = new javax.swing.JTextField();
        btn_batal = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_data = new javax.swing.JTable();
        btn_hapus = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        txt_namaPembeli = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 204, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Laundry Payment");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 220, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Bayar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 130, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Data Laundry");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 590, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Harga");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 130, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Berat/Kg");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 130, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Total Harga");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 130, 50));

        combo_jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis", "Cuci Basah", "Cuci Kering", "Cuci Setrika" }));
        combo_jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_jenisActionPerformed(evt);
            }
        });
        jPanel1.add(combo_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 220, 50));
        jPanel1.add(txt_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 270, 50));

        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 270, 50));

        txt_berat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_beratKeyReleased(evt);
            }
        });
        jPanel1.add(txt_berat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 270, 50));
        jPanel1.add(txt_ttlHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 270, 50));

        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 140, 50));

        btn_transaksi.setText("Transaksi");
        btn_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_transaksiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 140, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Nama Pembeli");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 130, 50));

        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_data);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 590, 470));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 640, 140, 50));

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 640, 140, 50));

        txt_namaPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaPembeliActionPerformed(evt);
            }
        });
        jPanel1.add(txt_namaPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 270, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setText("Jenis Cuci");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 130, 50));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1200, 810);

        setSize(new java.awt.Dimension(1218, 817));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void combo_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_jenisActionPerformed
        if (combo_jenis.getSelectedItem().equals("Pilih Jenis")) {
            txt_harga.setText("0");
        } else if (combo_jenis.getSelectedItem().equals("Cuci Basah")) {
            txt_harga.setText("3000");
        } else if (combo_jenis.getSelectedItem().equals("Cuci Kering")) {
            txt_harga.setText("4000");
        } else if (combo_jenis.getSelectedItem().equals("Cuci Setrika")) {
            txt_harga.setText("5000");
        }
    }//GEN-LAST:event_combo_jenisActionPerformed

    private void txt_beratKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_beratKeyReleased
        if (txt_berat.getText().equals("")) {
            txt_ttlHarga.setText("0");
        } else {
            int harga = Integer.parseInt(txt_harga.getText());
            int berat = Integer.parseInt(txt_berat.getText());
            Total_Harga = harga * berat;
            txt_ttlHarga.setText(String.valueOf(Total_Harga));
        }
    }//GEN-LAST:event_txt_beratKeyReleased

    private void btn_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_transaksiActionPerformed
        String url = "insert into data_laundry values (?,?,?,?,?,?,?,?)";
        if (txt_harga.getText().isEmpty() || txt_namaPembeli.getText().isEmpty() || txt_berat.getText().isEmpty() || txt_ttlHarga.getText().isEmpty() || txt_bayar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Isi terlebih dahulu semua kolom");
        } else {
            int bayar = Integer.parseInt(txt_bayar.getText());
            int kembalian = bayar - Total_Harga;

            try {
                PreparedStatement stat = conn.prepareStatement(url);
                stat.setString(1, null);
                stat.setString(2,txt_namaPembeli.getText());
                stat.setString(3, String.valueOf(combo_jenis.getSelectedItem()));
                stat.setString(4, txt_harga.getText());
                stat.setString(5, txt_berat.getText());
                stat.setString(6, txt_ttlHarga.getText());
                stat.setString(7, txt_bayar.getText());
                stat.setString(8, String.valueOf(kembalian));
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Kembalian Anda :\n" + kembalian);

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Transaksi Gagal" + e);
            }

            reset();
            Tampilkan_Data();
        }
    }//GEN-LAST:event_btn_transaksiActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        reset();
    }//GEN-LAST:event_btn_batalActionPerformed

    private void tabel_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_dataMouseClicked
        txt_namaPembeli.setText((String) tabel_data.getValueAt(tabel_data.getSelectedRow(), 1));
        combo_jenis.setSelectedItem(tabel_data.getValueAt(tabel_data.getSelectedRow(), 2));
        txt_harga.setText((String) tabel_data.getValueAt(tabel_data.getSelectedRow(), 3));
        txt_berat.setText((String) tabel_data.getValueAt(tabel_data.getSelectedRow(), 4));
        txt_ttlHarga.setText((String) tabel_data.getValueAt(tabel_data.getSelectedRow(), 5));
        txt_bayar.setText((String) tabel_data.getValueAt(tabel_data.getSelectedRow(), 6));
        field_id = Integer.parseInt((String) tabel_data.getValueAt(tabel_data.getSelectedRow(), 0));
    }//GEN-LAST:event_tabel_dataMouseClicked

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String JenisCuci = combo_jenis.getSelectedItem().toString();
        String Harga = txt_harga.getText();
        String Berat = txt_berat.getText();
        String TotalHarga = txt_ttlHarga.getText();
        String Bayar = txt_bayar.getText();
        String namaPembeli = txt_namaPembeli.getText();

        if (txt_namaPembeli.getText().isEmpty() || txt_harga.getText().isEmpty() || txt_berat.getText().isEmpty() || txt_ttlHarga.getText().isEmpty() || txt_bayar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lengkapi kolom terlebih dahulu!");
        } else {
            int Kembalian = Integer.parseInt(Bayar) - Integer.parseInt(TotalHarga);
            String sql = "update data_laundry set jenis_cuci='" + JenisCuci + "',harga='" + Harga + "',berat='" + Berat + "',total_harga='" + TotalHarga + "',bayar='" + Bayar + "',kembalian='" + Kembalian + "',namaPembeli='" + namaPembeli + "' where field_id=" + field_id + "";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data sudah berhasil diperbarui\n Kembalian anda: " + Kembalian);
            } catch (SQLException e) {
                Logger.getLogger("data gagal disimpan " + e);
            }
            Tampilkan_Data();
            reset();
        }

    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        if ((field_id) == 0) {
            JOptionPane.showMessageDialog(null, "Pilih data yang akan dihapus terlebih dahulu!");
        }else{
            String sql = "delete from data_laundry where field_id="+field_id+"";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
            } catch (SQLException e) {
                Logger.getLogger("Data gagal dihapus "+e);
            }
            Tampilkan_Data();
            reset();
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void txt_namaPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaPembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaPembeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Laundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Laundry().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> combo_jenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_data;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_berat;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_namaPembeli;
    private javax.swing.JTextField txt_ttlHarga;
    // End of variables declaration//GEN-END:variables
}
